### ISSUE TITLE
Non-interactive mode

### ISSUE THREAD

**Issue by ripleymj** [tslater2006/Pivet#12]
Brainstorming here, but this seems like something people would like as a scheduled task or cron job. If running like that, it should never prompt for input or try to do an "animated" (progress bar) output.

- [ ] Missing config file is a fatal error (don't prompt to create a new one)
- [ ] Progress bars are disabled
- [ ] Don't pause for input as the final step
- [ ] Others?

**Comment by tslater2006** [comment]
I like this idea. I recently added the -b flag to trigger the Config Builder (or edit the existing config). With this in place I think we can implement item 1 (missing config is fatal error)

Perhaps adding a -p flag for "show progress", this could be set as a globally accessible value, and if not set the ProfileRunner will not subscribe to the ProgressChanged events.

Currently the pause on the final step is to aid in running the code through Visual Studio, since without it the console window disappears immediately. But I agree it should be removed.
